version: '2'
services:
  ptbin:
    hostname: ptbin
    build: .
    ports:
        - "5050:3000"
    volumes:
        - .:/usr/src/app
        - node_modules:/usr/src/app/node_modules
    restart: always
    depends_on:
        - mariadb
    environment:
        - TZ=Asia/Shanghai
  mariadb:
    hostname: mariadb
    image: "mariadb:10.3"
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=ptbin
        - MYSQL_DATABASE=ptbin
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
    node_modules:
