version: '2'
services:
  ptbin:
    hostname: ptbin
    build: .
    ports:
        - "3000:3000"
    volumes:
        - .:/usr/src/app
    restart: always
    depends_on:
        - mariadb
  mariadb:
    hostname: mariadb
    image: "mariadb:10.3"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: "ptbin"
       MYSQL_DATABASE: "ptbin"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
